name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo yum update -y
          sudo yum install -y aws-cli
          sudo yum install -y httpd # Install Apache HTTP Server (httpd)
          sudo systemctl start httpd
          sudo systemctl enable httpd
          sudo yum install -y git # Install Git
          
      - name: Deploy to EC2
        run: |
          # Set AWS credentials
          aws configure set aws_access_key_id ${{ secrets.ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.SECRET_ACCESS_KEY}}
          aws configure set default.region us-east-1 # Replace with your desired region

          # Deploy your code to EC2 using your preferred method (e.g., SCP, S3 Sync, etc.)
          # Example using SCP:
          scp -r * ec2-user@35.170.202.193:/var/www/html

