name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Configure AWS CLI
        run: |
          # Set AWS credentials
          aws configure set aws_access_key_id ${{ secrets.ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1 # Replace with your desired region

      - name: Deploy to EC2
        run: |
          # Assuming you have your code in a specific directory, for example, 'dist/'
          scp -r dist/ ec2-user@54.161.244.24:/var/www/html/

